sudo: false

language:
  - python

python:
  - 2.7

install:
  - conda install -c conda-forge unicodecsv
  - conda install -c conda-forge easygui
  - conda install -c conda-forge statistics

script:
  
notifications:
  email: false